CREATE TABLE products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(64) NOT NULL,
    product_name VARCHAR(150) NOT NULL,
    product_description VARCHAR(2000),
    product_price NUMERIC(19, 2) NOT NULL CHECK (product_price >= 0),
    product_currency VARCHAR(3) NOT NULL,
    product_ava_qty INTEGER NOT NULL DEFAULT 0 CHECK (product_ava_qty >= 0),
    product_res_qty INTEGER NOT NULL DEFAULT 0 CHECK (product_res_qty >= 0),
    product_status VARCHAR(20) NOT NULL,
    product_version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_product_sku UNIQUE (sku),
    CONSTRAINT chk_product_status
        CHECK (product_status IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'DISCONTINUED'))
);

CREATE TABLE inventory_reservation (
    reservation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    confirmed_at TIMESTAMPTZ,
    released_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_inventory_reservation_order UNIQUE (order_id),
    CONSTRAINT chk_reservation_status
        CHECK (status IN ('RESERVED', 'CONFIRMED', 'RELEASED', 'EXPIRED', 'FAILED'))
);

CREATE TABLE inventory_reservation_item (
    reservation_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    sku VARCHAR(64) NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_reservation_item_reservation
        FOREIGN KEY (reservation_id) REFERENCES inventory_reservation (reservation_id),
    CONSTRAINT fk_reservation_item_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
);

CREATE TABLE stock_movement (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER NOT NULL,
    type VARCHAR(30) NOT NULL,
    quantity INTEGER NOT NULL,
    available_quantity_before INTEGER NOT NULL,
    available_quantity_after INTEGER NOT NULL,
    reserved_quantity_before INTEGER NOT NULL,
    reserved_quantity_after INTEGER NOT NULL,
    reference_type VARCHAR(30) NOT NULL,
    reference_id INTEGER,
    reason VARCHAR(500),
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_stock_movement_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
);

CREATE INDEX idx_inventory_reservation_order_id ON inventory_reservation (order_id);
CREATE INDEX idx_inventory_reservation_item_product_id ON inventory_reservation_item (product_id);
CREATE INDEX idx_stock_movement_product_id ON stock_movement (product_id);
